"""Prévisualisation du plan : fichiers qui seront écrits, diff exact de chacun, récapitulatif, actions dérivées.

Rien n'est écrit ici. Le bouton « Appliquer… » ouvre la boîte d'application.

Correction par rapport à FTOCompare : ``build_preview`` relit des fichiers, recalcule des
diffs et cherche les références sur tout le modèle ; il tournait dans le thread de
l'interface et pouvait la figer sur un gros projet. Il tourne désormais en arrière-plan,
sur une copie du plan (les options cochées pendant le calcul relancent un calcul).
"""

from __future__ import annotations

import copy
import logging
from pathlib import Path

from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QColor
from PySide6.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QMessageBox,
    QPushButton,
    QSplitter,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from ....common import theme, workers
from ....common.i18n import tr
from ..core.analysis import Comparison
from ....common.optix.text import split_lines
from ..core.plan import Plan, Preview, build_preview, load_plan, save_plan
from .diff_view import DiffView
from .style import taille_lisible

log = logging.getLogger(__name__)


class PlanDialog(QDialog):
    """Liste des fichiers à écrire + diff avant/après + récapitulatif + options."""

    apply_requested = Signal(object)  # Preview
    plan_loaded = Signal()

    def __init__(self, comparison: Comparison, plan: Plan, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setWindowTitle(tr("Plan preview — nothing is written at this stage"))
        self.resize(1300, 800)
        self.comparison = comparison
        self.plan = plan
        self.preview: Preview | None = None
        self._worker: workers.TaskWorker | None = None
        self._refresh_again = False

        self.summary = QLabel()
        self.summary.setTextFormat(Qt.TextFormat.RichText)
        self.summary.setWordWrap(True)

        self.files = QListWidget()
        self.files.currentItemChanged.connect(self._show_change)
        self.diff = DiffView()
        self.notes = QTextEdit()
        self.notes.setReadOnly(True)
        self.notes.setMaximumHeight(160)

        self.copy_stats = QCheckBox(tr("Copy the .optix statistics from the runtime (cosmetic, regenerated by the IDE)"))
        self.copy_stats.setChecked(plan.copier_statistiques)
        self.copy_stats.toggled.connect(self._option_changed)
        self.move_orphans = QCheckBox(tr("Move YAML files that became orphans to a discard folder (never deleted)"))
        self.move_orphans.setChecked(plan.deplacer_orphelins)
        self.move_orphans.toggled.connect(self._option_changed)

        self.save_button = QPushButton(tr("Save the plan…"))
        self.save_button.clicked.connect(self.save_plan_file)
        self.load_button = QPushButton(tr("Load a plan…"))
        self.load_button.clicked.connect(self.load_plan_file)
        self.apply_button = QPushButton(tr("Apply…"))
        self.apply_button.setProperty("accent", True)
        self.apply_button.setDefault(True)
        self.apply_button.clicked.connect(self._apply)
        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
        buttons.rejected.connect(self.reject)
        buttons.addButton(self.save_button, QDialogButtonBox.ButtonRole.ActionRole)
        buttons.addButton(self.load_button, QDialogButtonBox.ButtonRole.ActionRole)
        buttons.addButton(self.apply_button, QDialogButtonBox.ButtonRole.AcceptRole)

        right = QWidget()
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.addWidget(self.diff, 1)
        right_layout.addWidget(self.notes)
        splitter = QSplitter(Qt.Orientation.Horizontal)
        splitter.addWidget(self.files)
        splitter.addWidget(right)
        splitter.setSizes([480, 820])

        layout = QVBoxLayout(self)
        layout.addWidget(self.summary)
        layout.addWidget(splitter, 1)
        layout.addWidget(self.copy_stats)
        layout.addWidget(self.move_orphans)
        layout.addWidget(buttons)
        self.refresh()

    # -- Affichage ------------------------------------------------------------------

    def refresh(self) -> None:
        """Relance le calcul de la prévisualisation en arrière-plan."""
        if self._worker is not None:
            self._refresh_again = True
            return
        plan = copy.deepcopy(self.plan)  # le calcul ne voit pas les clics faits pendant qu'il tourne
        comparison = self.comparison
        self.apply_button.setEnabled(False)
        self.summary.setText(tr("Computing the preview…"))
        worker = workers.TaskWorker(lambda _progress, _cancel: build_preview(plan, comparison), self)
        worker.succeeded.connect(self._show_preview)
        worker.failed.connect(self._on_failed)
        worker.finished.connect(self._on_finished)
        self._worker = worker
        worker.start()

    @property
    def busy(self) -> bool:
        return self._worker is not None

    def wait_ready(self, timeout_ms: int = 60_000) -> bool:
        """Attend la fin du calcul en traitant les événements (tests, enchaînements)."""
        from PySide6.QtCore import QCoreApplication, QDeadlineTimer

        deadline = QDeadlineTimer(timeout_ms)
        while self.busy and not deadline.hasExpired():
            QCoreApplication.processEvents()
            if self._worker is not None:
                self._worker.wait(20)
        QCoreApplication.processEvents()
        return not self.busy

    def _on_finished(self) -> None:
        worker, self._worker = self._worker, None
        if worker is not None:
            worker.deleteLater()
        if self._refresh_again:
            self._refresh_again = False
            self.refresh()

    def _on_failed(self, message: str) -> None:
        self.summary.setText(f'<span style="color:{theme.current().error}">⚠ {message}</span>')

    def _show_preview(self, preview: Preview) -> None:
        if self._refresh_again:
            return  # un calcul plus récent va suivre
        self.preview = preview
        p = preview
        pal = theme.current()
        parts = [
            tr("<b>{n}</b> file(s) will be written").format(n=len(p.changes)),
            f'<span style="color:{pal.success}">➕ ' + tr("<b>{n}</b> additions").format(n=p.nb_ajouts) + "</span>",
            f'<span style="color:{pal.error}">➖ ' + tr("<b>{n}</b> removals").format(n=p.nb_retraits) + "</span>",
            f'<span style="color:{pal.warning}">✏️ ' + tr("<b>{n}</b> values").format(n=p.nb_valeurs) + "</span>",
        ]
        if p.types_retires:
            parts.append(tr("{n} type(s) pruned by GUID").format(n=len(p.types_retires)))
        if p.orphelins:
            parts.append(tr("{n} orphan YAML file(s)").format(n=len(p.orphelins)))
        text = "  ·  ".join(parts)
        if p.avertissements:
            text += "<br>" + "<br>".join(f'<span style="color:{pal.error}">⚠ {a}</span>' for a in p.avertissements)
        self.summary.setText(text)
        self.files.clear()
        for change in p.changes:
            item = QListWidgetItem(
                f"{change.rel}\n    {change.origine} — {taille_lisible(change.taille_avant)} → {taille_lisible(change.taille_apres)}"
                f"  (+{change.nb_ajouts} / −{change.nb_retraits} / ✏️{change.nb_valeurs})"
            )
            item.setData(Qt.ItemDataRole.UserRole, change.rel)
            self.files.addItem(item)
        for rel in p.orphelins:
            detail = tr("→ discard folder") if self.plan.deplacer_orphelins else tr("orphan left in place")
            item = QListWidgetItem(f"{rel}\n    {detail}")
            item.setData(Qt.ItemDataRole.UserRole, "")
            item.setForeground(QColor(theme.current().text_muted))
            self.files.addItem(item)
        self.apply_button.setEnabled(bool(p.changes) or bool(p.orphelins and self.plan.deplacer_orphelins))
        if self.files.count():
            self.files.setCurrentRow(0)
        else:
            self.diff.clear()
            self.notes.setPlainText(tr("No “take the runtime” decision: nothing would be written."))

    def _show_change(self, current: QListWidgetItem | None, _previous) -> None:
        if current is None:
            return
        rel = current.data(Qt.ItemDataRole.UserRole)
        change = self.preview.change(rel) if rel and self.preview is not None else None
        if change is None:
            self.diff.clear()
            self.notes.setPlainText(tr("File moved to the discard folder, content unchanged."))
            return
        old_lines = split_lines(change.old).lines
        new_lines = split_lines(change.new).lines
        self.diff.set_content(
            old_lines, new_lines, change.opcodes(), f"<b>{change.rel}</b> — " + tr("before (left) → after (right)")
        )
        lines = [tr("Origin: {origin}").format(origin=change.origine)] + [f"• {n}" for n in change.notes]
        refs = [r for r in self.preview.references if r.rel == change.rel]
        if refs:
            lines.append(tr("Remaining references in this file ({n}):").format(n=len(refs)))
            lines += [f"  l.{r.line_no} {r.name} : {r.text}" for r in refs[:20]]
        self.notes.setPlainText("\n".join(lines))

    def _option_changed(self) -> None:
        self.plan.copier_statistiques = self.copy_stats.isChecked()
        self.plan.deplacer_orphelins = self.move_orphans.isChecked()
        self.refresh()

    # -- Plan JSON -----------------------------------------------------------------------

    def save_plan_file(self, chemin: str | None = None) -> str | None:
        if not chemin:
            defaut = str(self.comparison.projet_root.parent / "FTOCompare_plan.json")
            chemin, _ = QFileDialog.getSaveFileName(self, tr("Save the plan"), defaut, tr("Compare plan (*.json)"))
        if not chemin:
            return None
        save_plan(self.plan, chemin, self.comparison)
        log.info("Plan enregistré : %s", chemin)
        return chemin

    def load_plan_file(self, chemin: str | None = None) -> list[str] | None:
        if not chemin:
            chemin, _ = QFileDialog.getOpenFileName(
                self, tr("Load a plan"), str(self.comparison.projet_root.parent), tr("Compare plan (*.json)")
            )
        if not chemin:
            return None
        plan, perdus = load_plan(chemin, self.comparison)
        self.plan.decisions = plan.decisions
        self.plan.alignement_complet = plan.alignement_complet
        self.plan.copier_statistiques = plan.copier_statistiques
        self.plan.deplacer_orphelins = plan.deplacer_orphelins
        self.copy_stats.setChecked(plan.copier_statistiques)
        self.move_orphans.setChecked(plan.deplacer_orphelins)
        self.refresh()
        self.plan_loaded.emit()
        if perdus:
            QMessageBox.warning(
                self, tr("Plan partly replayed"), tr("Differences not found in this comparison:") + "\n" + "\n".join(perdus)
            )
        log.info("Plan chargé : %s (%d décision(s), %d perdue(s))", chemin, len(plan.decisions), len(perdus))
        return perdus

    def _apply(self) -> None:
        if self.preview is not None and not self.busy:
            self.apply_requested.emit(self.preview)

    def done(self, result: int) -> None:  # noqa: D401 (API Qt)
        """À la fermeture, un calcul encore en cours est abandonné sans être attendu."""
        if self._worker is not None:
            self._worker.succeeded.disconnect()
            workers.retire(self._worker)
            self._worker = None
        super().done(result)
